baseURL = 'https://alecvdp.github.io/'
languageCode = 'en-us'
theme = 'terminal'
paginate = 5

[params]
  # IMPORTANT: these settings should ensure correct colors
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLanguageSelector = false
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Alec van der Poel"
    subtitle = "so it goes."
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Alec van der Poel"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
