baseURL = 'https://alecvdp.github.io/'
languageCode = 'en-us'
title = 'Alec van der Poel'
theme = 'terminal'

[params]
    themeColor = "blue"
    images = "/images/xmasdoggo.png"
    fullWidthTheme = false
    centerTheme = true





[languages]
    [languages.en]
        languageName = "English"
        title = "Alec van der Poel"
        subtitle = "so it goes."
        owner = "Alec van der Poel"
        keywords = ""
        copyright = ""
        menuMore = "Show more"
        readMore = "Read more"
        readOtherPosts = "Read other posts"


        [languages.en.params.logo]
            logoText = "czander"
            logoHomelink = "/"
        [languages.en.menu]
            [[languages.en.menu.main]]
                identifier = "about"
                name = "About"
                url = "/about"
