baseURL = "https://alecvdp.github.io/"
title = "czander"
theme = "blowfish"

defaultContentLanguage = "en"
enableRobotsTXT = true

[params]
  colorScheme = "dark"
  defaultAppearance = "dark"
  autoSwitchAppearance = false

[params.homepage]
  layout = "profile"
  showRecent = false
  showSocialLinks = true

[params.author]
  name = "Alec van der Poel"
  headline = "so it goes."
  # Fix the image path format
  image = "/hehe.jpeg"
  links = [
    { github = "https://github.com/alecvdp" },
    { linkedin = "https://www.linkedin.com/in/alec-van-der-poel-a3bb9051" },
    { lastfm = "https://last.fm/user/czander_" },
    { email = "mailto:alecvdpoel@pm.me" }
  ]

[params.footer]
  showCopyright = true    
  showThemeAttribution = false   

[menu]
  [[menu.main]]
    name = "About"
    pageRef = "about"
    weight = 10
  [[menu.main]]
    name = "Blog"
    pageRef = "blog"
    weight = 20
  [[menu.main]]
    name = "Projects"
    pageRef = "projects"
    weight = 30


