baseURL = 'https://alecvdp.github.io/'
languageCode = 'en-us'
title = 'czander'
theme = 'poison'

[params]
    brand = "czander"    # This shows in the header
    brand_image = "/images/xmasdoggo.png"       # Optional: leave empty for text-only header
    description = "it's me, it's my site"
    dark_mode = true

    # Social links - delete any you don't want
    github_url = "https://github.com/alecvdp"
    # twitter_url = ""
    linkedin_url = "www.linkedin.com/in/alec-van-der-poel-a3bb9051"
    email_url = "alecvdpoel@pm.me"

    front_page_content = ["posts"]

[languages]
    [languages.en]
        languageName = "English"

        [languages.en.params.author]
            name = "czander"
            url = "https://github.com/alecvdp"    # Optional: your homepage/blog/about page
