baseURL = "https://alecvdp.github.io/"  # Your actual URL
title = "Your Name"
theme = "PaperMod"

[params]
    defaultTheme = "dark"

[params.profileMode]
    enabled = true
    title = "czander"     # The main headline
    subtitle = "so it goes."
    imageUrl = "/images/xmasdoggo.png"  # Your profile picture

[[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/alecvdp"
    # We can add more social icons like:
    # LinkedIn, Email, Twitter, etc.
