baseURL = "https://alecvdp.github.io/"  # Your actual URL
title = "Alec van der Poel"
theme = "PaperMod"

[params]
    defaultTheme = "dark"

[params.profileMode]
    enabled = true
    title = "czander"     # The main headline
    subtitle = "so it goes."
    imageUrl = "/images/alec-uniform.jpg"  # Your profile picture

[[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/alecvdp"
    # We can add more social icons like:
    # LinkedIn, Email, Twitter, etc.
