baseURL = "https://alecvdp.github.io/"  # Your actual URL
title = "Alec van der Poel"
theme = "PaperMod"

[params]
    defaultTheme = "dark"

[params.profileMode]
    enabled = true
    title = "czander"     # The main headline
    subtitle = "so it goes."
    imageUrl = "/images/hehe.jpeg"  # Your profile picture

[[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/alecvdp"
[[params.socialIcons]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/alec-van-der-poel-a3bb9051" 
[[params.socialIcons]]
    name = "lastfm"
    url = "https://last.fm/user/czander_" 
[[params.socialIcons]]
    name = "letterboxd"
    url = "https://letterboxd.com/alecvdpoel"

    # We can add more social icons like:
    # LinkedIn, Email, Twitter, etc.
